#!/usr/bin/env bash

servicedir='./service'
procdir='./proc'

mkdir -p "$servicedir"
mkdir -p "$procdir"

make-service() {
	local name=$1
	local state=$2
	local pid=$3

	local dir=$servicedir/$name

	echo "creating $dir: (pid '$pid' state '$state')"

	mkdir -p "$dir"
	mkdir -p "$dir/supervise"
	echo "$state" > "$dir/supervise/stat"
	echo "$pid" > "$dir/supervise/pid"

	local proc=$procdir/$pid
	echo "creating $proc"
	mkdir -p "$proc"
	printf '%s-command\0arg1\0arg2\0' "$name" > "$proc/cmdline"
}

make-service 'foo' 'run' 123
make-service 'bar' 'run' 456
make-service 'baz' 'run' 65537
