[package]
name = "vsv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.1.0", features = ["cargo", "derive"] }
dirs = "4.0.0"
libc = "0.2.118"
rayon = "1.5.1"
yansi = "0.5.0"

[features]
