[package]
name = "vsv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.0.14", features = ["cargo", "derive"] }
lazy_static = "1.4.0"
libc = "0.2"
rayon = "1.5.1"
yansi = "0.5.0"

[features]
